// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PC_ML_Core
{
    public partial class PCModel
    {
        /// <summary>
        /// model input class for PCModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"CPU")]
            public string CPU { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"GHz")]
            public float GHz { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"GPU")]
            public string GPU { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"RAM")]
            public float RAM { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"RAMType")]
            public string RAMType { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Screen")]
            public float Screen { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Storage")]
            public float Storage { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"SSD")]
            public bool SSD { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PCModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CPU")]
            public float[] CPU { get; set; }

            [ColumnName(@"GHz")]
            public float GHz { get; set; }

            [ColumnName(@"GPU")]
            public float[] GPU { get; set; }

            [ColumnName(@"RAM")]
            public float RAM { get; set; }

            [ColumnName(@"RAMType")]
            public float[] RAMType { get; set; }

            [ColumnName(@"Screen")]
            public float Screen { get; set; }

            [ColumnName(@"Storage")]
            public float Storage { get; set; }

            [ColumnName(@"SSD")]
            public float[] SSD { get; set; }

            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PCModel.mlnet");
        public static string BaseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        public static string MModelPath = Path.Combine(BaseDirectory, "PCModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        public static IDataView? ModelData { get; private set; }
        public static DataOperationsCatalog? Data { get; private set; }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MModelPath, out var schema);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
